//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/ControlesJuego.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControlesJuego: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControlesJuego()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControlesJuego"",
    ""maps"": [
        {
            ""name"": ""ShootingActions"",
            ""id"": ""9ae68463-56a2-4b57-82d5-583ba3c4c3dd"",
            ""actions"": [
                {
                    ""name"": ""Disparar"",
                    ""type"": ""Button"",
                    ""id"": ""4081ad50-9d3e-4249-b711-76d06f05d7c2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Posicion"",
                    ""type"": ""Value"",
                    ""id"": ""17dc9a2f-1dd3-4bab-af76-f696943d0c6a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fdc7b905-94a5-4ec2-a0f2-75672c634482"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Disparar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d54c3ff5-c8c3-4f44-a069-f679634a8095"",
                    ""path"": ""<Touchscreen>/primaryTouch/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Disparar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f8aba24-630d-4c64-9801-35d4dd11e144"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Posicion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dda5113e-4d27-4519-b45d-672e5ffb296f"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Posicion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ShootingActions
        m_ShootingActions = asset.FindActionMap("ShootingActions", throwIfNotFound: true);
        m_ShootingActions_Disparar = m_ShootingActions.FindAction("Disparar", throwIfNotFound: true);
        m_ShootingActions_Posicion = m_ShootingActions.FindAction("Posicion", throwIfNotFound: true);
    }

    ~@ControlesJuego()
    {
        UnityEngine.Debug.Assert(!m_ShootingActions.enabled, "This will cause a leak and performance issues, ControlesJuego.ShootingActions.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ShootingActions
    private readonly InputActionMap m_ShootingActions;
    private List<IShootingActionsActions> m_ShootingActionsActionsCallbackInterfaces = new List<IShootingActionsActions>();
    private readonly InputAction m_ShootingActions_Disparar;
    private readonly InputAction m_ShootingActions_Posicion;
    public struct ShootingActionsActions
    {
        private @ControlesJuego m_Wrapper;
        public ShootingActionsActions(@ControlesJuego wrapper) { m_Wrapper = wrapper; }
        public InputAction @Disparar => m_Wrapper.m_ShootingActions_Disparar;
        public InputAction @Posicion => m_Wrapper.m_ShootingActions_Posicion;
        public InputActionMap Get() { return m_Wrapper.m_ShootingActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ShootingActionsActions set) { return set.Get(); }
        public void AddCallbacks(IShootingActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_ShootingActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ShootingActionsActionsCallbackInterfaces.Add(instance);
            @Disparar.started += instance.OnDisparar;
            @Disparar.performed += instance.OnDisparar;
            @Disparar.canceled += instance.OnDisparar;
            @Posicion.started += instance.OnPosicion;
            @Posicion.performed += instance.OnPosicion;
            @Posicion.canceled += instance.OnPosicion;
        }

        private void UnregisterCallbacks(IShootingActionsActions instance)
        {
            @Disparar.started -= instance.OnDisparar;
            @Disparar.performed -= instance.OnDisparar;
            @Disparar.canceled -= instance.OnDisparar;
            @Posicion.started -= instance.OnPosicion;
            @Posicion.performed -= instance.OnPosicion;
            @Posicion.canceled -= instance.OnPosicion;
        }

        public void RemoveCallbacks(IShootingActionsActions instance)
        {
            if (m_Wrapper.m_ShootingActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IShootingActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_ShootingActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ShootingActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ShootingActionsActions @ShootingActions => new ShootingActionsActions(this);
    public interface IShootingActionsActions
    {
        void OnDisparar(InputAction.CallbackContext context);
        void OnPosicion(InputAction.CallbackContext context);
    }
}
